### ISSUE TITLE
Pacific/Fiji not adjusted for delayed DST change.

### ISSUE THREAD

**Issue by teelau** [moment/moment-timezone#905]
In 2020 the Pacific/Fiji is delaying it's start of DST to December 20, 2017 2AM. 

https://www.timeanddate.com/news/time/fiji-starts-dst-2020.html

It looks like we aren't updated to the latest changes for this time zone for moment-timezone.

```
fiji = moment.tz("Pacific/Fiji")
fiji.dayOfYear(313).format()
"2020-11-08T12:39:52+13:00"
fiji.dayOfYear(312).format()
"2020-11-07T12:39:52+12:00"
```

**Comment by ellenaua** [comment]
Hi @teelau please upgrade to version 0.5.32 we released today

**Comment by mark-henry** [comment]
I upgraded to 0.5.32 but this issue is still reproducible for me.

`fiji = moment.tz("Pacific/Fiji")
fiji.dayOfYear(313).format()
"2020-11-08T14:33:33+13:00"
fiji.dayOfYear(312).format()
"2020-11-07T14:33:33+12:00"
moment.tz.version
"0.5.32"`

It is expected that both of these should have +12 as the changeover is delayed.

@teelau is the issue still reproducible for you?

**Comment by mark-henry** [comment]
@ellenaua can you tell me how to run the tests in moment-timezone? I want to verify that .32 has the fix. The Gruntfile has 'typing-tests' but I want to run the big timezone test suite.

**Comment by dexwiz** [comment]
@ellenaua It seems like the build files were not properly updated. They still reference the 2020a IANA database. https://github.com/moment/moment-timezone/blob/master/builds/moment-timezone-with-data.js#L694 Also the fiji updates are missing from the data.

**Comment by mark-henry** [comment]
It appears that the 10-year-range files were not updated or were updated incorrectly in the 0.5.32 release.

```
mhenry-ltm1:moment-timezone mark.henry$ git reset --hard 0.5.32
HEAD is now at 3128dda IANA timezone database 2020d (#910)
mhenry-ltm1:moment-timezone mark.henry$ grunt build
Running "build:moment-timezone-with-data" (build) task

Running "build:moment-timezone-with-data-1970-2030" (build) task

Running "build:moment-timezone-with-data-2012-2022" (build) task

Running "build:moment-timezone-with-data-10-year-range" (build) task

Done.
mhenry-ltm1:moment-timezone mark.henry$ git diff
diff --git a/builds/moment-timezone-with-data-10-year-range.js b/builds/moment-timezone-with-data-10-year-range.js
index 9764735..c0db784 100644
--- a/builds/moment-timezone-with-data-10-year-range.js
+++ b/builds/moment-timezone-with-data-10-year-range.js
@@ -691,7 +691,7 @@
        }
 
        loadData({
-               "version": "2020a",
+               "version": "2020d",
                "zones": [
                        "Africa/Abidjan|GMT|0|0||48e5",
                        "Africa/Nairobi|EAT|-30|0||47e5",
@@ -699,7 +699,7 @@
```
...
```
"Pacific/Fiji|+13 +12|-d0 -c0|01010101010101010101010|1NF20 1SM0 uM0 1VA0 s00 1VA0 s00 1VA0 s00 20o0 pc0 20o0 s00 20o0 pc0 20o0 pc0 20o0 pc0 20o0 pc0 20o0|88e4",
+                       "Pacific/Fiji|+13 +12|-d0 -c0|01010101010101010101010|1NF20 1SM0 uM0 1VA0 s00 1VA0 s00 1VA0 s00 20o0 pc0 2hc0 bc0 20o0 pc0 20o0 pc0 20o0 pc0 20o0 pc0 20o0|88e4",
                        "Pacific/Guam|ChST|-a0|0||17e4",
```

**Comment by ichernev** [comment]
@teelau @mark-henry can you please verify if the latest version 0.5.37 (based on 2022c) fixes your issue? There were some bugs in the pipeline that were resolved.

**Comment by ichernev** [comment]
Seems fixed, closing.
